name: CI
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy:
    uses:
      ./.github/workflows/deploy.yml
    with:
      environment: dev
    secrets:
      aws-role-arn: ${{ secrets.AWSROLE_HARBOURBOOKS_GITHUBACTIONS }}
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}


